name: melos_workspace
sdkPath: .fvm/flutter_sdk
# Melos runs Flutter from the sdkPath specified above
# Which means that usage of `fvm` shouldn't be necessary and is discouraged inside melos script definitions.
# If melos doesn't proxy to the correct Flutter SDK, you can try reapplying `fvm dart pub global activate melos` again

packages:
  - app
  - packages/**

command:
  bootstrap:
    environment:
      sdk: ">=3.7.2 <4.0.0"
    dependencies:
      # External Dependencies
      flutter:
        sdk: flutter
      cupertino_icons: ^1.0.8
      # RP Dependencies

    dev_dependencies:
      flutter_lints: ^4.0.0
      flutter_test:
        sdk: flutter

scripts:
  fix:
    description: Apply automatically fixes into dart code.
    run: dart fix . --apply

  fix_dry:
    description: Detect possible fixes into dart code, no modification is done.
    run: dart fix . --dry-run

  format:check:
    description: Check formatting of Dart code.
    exec: dart format -l 120 --output none --set-exit-if-changed .

  analyze:check:
    description: Analyze Dart code.
    run: dart analyze . --fatal-infos

  outdated_deps:
    description: Identify out-of-date package dependencies and get advice on how to update them.
    run: dart pub outdated

  test:
    description: Run `flutter test` in all packages
    run: flutter test
